using System.Reflection;
using System.Text;
using CaseConverter;
using LEGO.AsyncAPI.Models;
using LEGO.AsyncAPI.Readers;

namespace AsyncAPI.Saunter.Generator.Cli.FromSpec.AsyncApiInterface;

internal interface IAsyncApiGenerator
{
    string GenerateAsyncApiInterfaces(GeneratorOptions options, string text, AsyncApiState state);

    string GenerateAsyncApiInterfaces(GeneratorOptions options, AsyncApiDocument asyncApi, AsyncApiState state);
}

internal class AsyncApiGenerator : IAsyncApiGenerator
{
    private readonly string _version;
    private readonly string _name;

    public AsyncApiGenerator()
    {
        var assembly = Assembly.GetExecutingAssembly().GetName();

        this._version = assembly.Version!.ToString();
        this._name = assembly.Name;
    }

    private static string MakeGlobalDocumentTopic(string name) => $"TOPIC_{name.ToSnakeCase().ToUpperInvariant()}";

    public string GenerateAsyncApiInterfaces(GeneratorOptions options, string text, AsyncApiState state)
    {
        var asyncApi = new AsyncApiStringReader().Read(text, out var diagnostic);
        return this.GenerateAsyncApiInterfaces(options, asyncApi, state);
    }

    public string GenerateAsyncApiInterfaces(GeneratorOptions options, AsyncApiDocument asyncApi, AsyncApiState state)
    {
        var sb = new StringBuilder(
            $$"""
              //----------------------
              // <auto-generated>
              //     Generated using {{this._name}} v{{this._version}}
              //     At: {{DateTime.Now:U}}  
              // </auto-generated>
              //----------------------
          
              using Saunter.Attributes;
              using System.CodeDom.Compiler;
          
              namespace {{options.Namespace}}
              {
              {{this.GetGeneratedCodeAttributeLine()}}
                  public static partial class {{options.TopicsClassName}}
                  {
              """);

        sb.AppendLine();
        sb.AppendLine($"        public const string {MakeGlobalDocumentTopic(options.ClassName)} = \"{options.ClassName.ToPascalCase()}\";");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Commands
        this.AddInterface(sb, options, options.ClassName, $"{options.ClassName}Commands", new("SubscribeOperation", "command", x => x.Subscribe), asyncApi.Channels.Where(x => x.Value.Subscribe != null));
        sb.AppendLine();

        // Events
        this.AddInterface(sb, options, options.ClassName, $"{options.ClassName}Events", new("PublishOperation", "evt", x => x.Publish), asyncApi.Channels.Where(x => x.Value.Publish != null));
        
        sb.AppendLine("}"); // close namespace
        sb.AppendLine();

        state.Documents.Add(options.ClassName);
        var contents = sb.ToString();
        return contents;
    }

    private string GetGeneratedCodeAttributeLine() => $"    [GeneratedCodeAttribute(\"{this._name}\", \"{this._version}\")]";

    private void AddInterface(StringBuilder sb, GeneratorOptions genOptions, string specName, string className, OperationOptions options, IEnumerable<KeyValuePair<string, AsyncApiChannel>> channels)
    {
        sb.AppendLine($"    [AsyncApi({genOptions.TopicsClassName}.{MakeGlobalDocumentTopic(specName)})]");
        sb.AppendLine(this.GetGeneratedCodeAttributeLine());
        sb.AppendLine($"    public interface I{className}");
        sb.Append("    {");

        foreach (var channel in channels)
        {
            AddChannelOperation(sb, options, channel);
        }

        sb.AppendLine("    }");
    }

    private record OperationOptions(string OperationAttribute, string VarName, Func<AsyncApiChannel, AsyncApiOperation> OperationProvider);

    private static void AddChannelOperation(StringBuilder sb, OperationOptions options, KeyValuePair<string, AsyncApiChannel> channel)
    {
        var operation = options.OperationProvider(channel.Value);

        sb.AppendLine();
        sb.AppendLine($"        [Channel(\"{channel.Key}\")]");
        var channelParametersSb = new StringBuilder();
        foreach (var channelParameter in channel.Value.Parameters)
        {
            var refName = FromReference(channelParameter.Value.Reference.Reference);
            var typeName = refName.ToPascalCase();
            if (channelParameter.Value.Schema.Enum.Any())
            {
                typeName += "s";
            }
            var varName = refName.ToCamelCase();
            sb.AppendLine($"        [ChannelParameter(\"{channelParameter.Key}\", typeof({typeName}), Description = \"{channelParameter.Value.Description}\")]");

            channelParametersSb.Append(", ");
            channelParametersSb.Append(typeName);
            channelParametersSb.Append(" ");
            channelParametersSb.Append(varName);
        }

        var msg = operation.Message.Single();
        var msgTypeName = (msg.Name ?? msg.Payload.Reference.Id).ToPascalCase();
        sb.AppendLine($"        [{options.OperationAttribute}(typeof({msgTypeName}), Summary = \"{operation.Summary}\", Description = \"{operation.Description}\")]");
        sb.Append($"        void {operation.OperationId}({msgTypeName} {options.VarName}");
        sb.Append(channelParametersSb);
        sb.AppendLine(");");
    }

    private static string FromReference(string reference)
    {
        var prefix = "#/components/parameters/";
        if (reference.IndexOf(prefix) == 0)
        {
            return reference[prefix.Length..];
        }
        throw new ArgumentException($"Invalid reference: {reference}");
    }
}
